name: Deploy

on:
  pull_request:
    branches: [kubot.deno.dev]
  push:
    branches: [kubot.deno.dev]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: kubot

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Load dotenv from github vars
        run: >
          echo """${{vars.DOTENV_CONTENT}}""" > .env

      - name: Extend (optionally) override dotenv from github secrets
        run: >
          echo """${{secrets.DOTENV_CONTENT}}""" >> .env

      # - name: Install Node.js for ui building
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: lts/*

      - name: install
        run: deno task install

      # - name: spa install
      #   run: cd spa && npm install

      # - name: spa build
      #   run: cd spa && npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: kubot
          entrypoint: "main.ts"
          root: ""
